#! /bin/sh

##Auto start
sxhkd -c $HOME/.config/bspwm/sxhkdrc >> /dev/null &
polybar -r example &
xrdb -load $HOME/.Xresources
#xwallpaper --focus /path/to/file
setxkbmap pl
dunst >> /dev/null &
picom&
bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config focused_border_color $nord15
bspc config normal_border_color  $nord2
bspc config window_gap           5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_follows_pointer true
#bspc config active_border_color $nord4 #two or more monitor set up

##Window rules
bspc rule -a Firefox desktop='^2' follow=on border=off
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gnome-Screenshot state=floating
bspc rule -a Alacritty state=floating rectangle=1000x600+200+150
#bspc rule -a Chromium desktop='^2'
